spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/journeydb
      username: journey
      password: journey
    jpa:
      hibernate:
        ddl-auto: update
    elasticsearch:
      rest:
        connection-timeout: 1s
        uris: localhost:9200
        read-timeout: 1m
        password:
        username:
